{"name": "渠道管理类", "status": "broken", "statusDetails": {"message": "Exception: error happend", "trace": "self = <testcases.test_02.Test2 object at 0x10e572470>\n\n    def test_4(self):\n        with allure.step('输出'):\n>           raise Exception('error happend')\nE           Exception: error happend\n\ntest_02.py:23: Exception"}, "description": "渠道管理描述", "steps": [{"name": "输出", "status": "broken", "statusDetails": {"message": "Exception: error happend\n", "trace": "  File \"/Users/ppll/Desktop/test/testcases/test_02.py\", line 23, in test_4\n    raise Exception('error happend')\n"}, "start": 1563036011774, "stop": 1563036011774}], "start": 1563036011774, "stop": 1563036011775, "uuid": "1ab804da-4b61-49eb-b394-360dec0e9c4d", "historyId": "14220c630e201a74973ff5ac6fcc3e95", "fullName": "test_02.Test2#test_4", "labels": [{"name": "story", "value": "渠道管理story"}, {"name": "feature", "value": "基础平台"}, {"name": "parentSuite"}, {"name": "suite", "value": "test_02"}, {"name": "subSuite", "value": "Test2"}, {"name": "host", "value": "pplldemac-mini"}, {"name": "thread", "value": "9762-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_02"}]}